# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: mantrae
report_sizes: true
pro: false

before:
  hooks:
    - rm -rf ./dist
    - go fmt ./...
    - go vet ./...
    - go mod tidy
    - go mod verify

builds:
  - id: server
    binary: mantrae
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Version={{.Tag}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Commit={{.Commit}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: agent
    main: ./agent/cmd/
    binary: mantrae_agent
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Version={{.Tag}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Commit={{.Commit}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

upx:
  - enabled: true

source:
  enabled: true

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  mode: keep-existing


archives:
  - id: server
    ids: [server]
    files:
      - LICENSE
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: agent
    ids: [agent]
    files:
      - LICENSE
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    include:
      - '^feat:'
      - '^fix:'
      - '^sec:'
      - '^doc:'
      - '^wip:'
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🔒 Security"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🐛 Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "📚 Documentation"
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "🚧 Work in progress"
      regexp: '^.*?wip(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: "🏷️ Other changes"
      regexp: '^.*?chore(\([[:word:]]+\))??!?:.+$'
      order: 5
    - title: Misc
      order: 999
