# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: mantrae
report_sizes: true

before:
  hooks:
    - rm -rf ./dist
    - go fmt ./...
    - go vet ./...
    - go mod tidy
    - go mod verify

builds:
  - id: server
    binary: mantrae
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Version={{.Tag}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Commit={{.Commit}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: agent
    main: ./agent/cmd/
    binary: mantrae_agent
    env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Version={{.Tag}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Commit={{.Commit}}
      - -X github.com/MizuchiLabs/mantrae/pkg/build.Date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

kos:
  - id: server
    build: server
    base_image: alpine
    repositories: ["ghcr.io/MizuchiLabs/mantrae"]
    sbom: spdx
    tags:
      - latest
      - "{{ if not .IsSnapshot }}{{.Tag}}{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "mantrae"
      org.opencontainers.image.description: "Mantrae Server"
      org.opencontainers.image.version: "{{.Tag}}"
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.source: "https://github.com/MizuchiLabs/mantrae"
    bare: true
    preserve_import_paths: false

  - id: agent
    build: agent
    base_image: alpine
    repositories: ["ghcr.io/MizuchiLabs/mantrae-agent"]
    sbom: spdx
    tags:
      - latest
      - "{{ if not .IsSnapshot }}{{.Tag}}{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      org.opencontainers.image.title: "mantrae-agent"
      org.opencontainers.image.description: "Mantrae Agent"
      org.opencontainers.image.version: "{{.Tag}}"
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.source: "https://github.com/MizuchiLabs/mantrae"
    bare: true
    preserve_import_paths: false

signs:
  - artifacts: checksum

docker_signs:
  - artifacts: manifests

upx:
  - enabled: true

source:
  enabled: true

release:
  draft: true
  replace_existing_draft: true
  replace_existing_artifacts: true
  mode: keep-existing

archives:
  - id: server
    formats: ["tar.gz"]
    builds: ["server"]
    files:
      - LICENSE
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: agent
    formats: ["tar.gz"]
    builds: ["agent"]
    files:
      - LICENSE
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    include:
      - '^feat:'
      - '^bug:'
      - '^sec:'
      - '^doc:'
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🔒 Security"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🐛 Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "📚 Documentation"
      regexp: '^.*?doc(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Misc
      order: 999
