# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: mantrae
dist: builds

before:
  hooks:
    - go fmt ./...
    - go vet ./...
    - go mod tidy
    - go mod verify
    - cd web && pnpm install && pnpm run build

builds:
  - id: server
    main: main.go
    binary: mantrae
    ldflags: -s -w -X github.com/MizuchiLabs/mantrae/pkg/util.Version={{.Version}} -X github.com/MizuchiLabs/mantrae/pkg/util.BuildDate={{.Date}} -X github.com/MizuchiLabs/mantrae/pkg/util.Commit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: agent
    main: ./agent/cmd/main.go
    binary: mantrae-agent
    ldflags: -s -w -X github.com/MizuchiLabs/mantrae/agent/client.Version={{.Version}} -X github.com/MizuchiLabs/mantrae/agent/client.BuildDate={{.Date}} -X github.com/MizuchiLabs/mantrae/agent/client.Commit={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

upx:
  - enabled: true

release:
  draft: true
  replace_existing_draft: true
  mode: replace

archives:
  - format: binary
    name_template: >-
      {{ .Binary }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

snapshot:
  version_template: '{{ incpatch .Version }}-next'

report_sizes: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^web:'
