openapi: 3.1.0
info:
  title: Mantrae
  description: |
    Mantrae API Documentation
    For more information, visit the [Documentation](https://mantrae.pages.dev)
  version: v1.0.0
  contact:
    name: Mantrae Support
    url: https://mantrae.pages.dev
    email: support@mizuchi.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
