services:
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.httpbin.rule=Host(`httpbin.example.com`)
      - traefik.http.routers.httpbin.entrypoints=web
    restart: always
