services:
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - 3001:80
    labels:
      #- traefik.enable=true
      - traefik.http.routers.httpbin.rule=Host(`httpbin.example.com`)
      - traefik.http.routers.httpbin.entrypoints=websecure
      - traefik.http.services.httpbin.loadbalancer.server.port=80
    restart: always

  traefik:
    image: docker.io/traefik:latest
    container_name: traefik
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true # Remove me later
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --serversTransport.insecureSkipVerify=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.watch=true
      - --providers.http.endpoint=http://host.docker.internal:3000/api/default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.entrypoints=websecure
    restart: always

networks:
  proxy:

