// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dns_providers.sql

package db

import (
	"context"

	"github.com/mizuchilabs/mantrae/server/internal/store/schema"
)

const countDnsProviders = `-- name: CountDnsProviders :one
SELECT
  COUNT(*)
FROM
  dns_providers
`

func (q *Queries) CountDnsProviders(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countDnsProvidersStmt, countDnsProviders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDnsProvider = `-- name: CreateDnsProvider :one
INSERT INTO
  dns_providers (
    id,
    name,
    type,
    config,
    is_default,
    created_at,
    updated_at
  )
VALUES
  (
    ?,
    ?,
    ?,
    ?,
    ?,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ) RETURNING id, name, type, config, is_default, created_at, updated_at
`

type CreateDnsProviderParams struct {
	ID        string                    `json:"id"`
	Name      string                    `json:"name"`
	Type      int64                     `json:"type"`
	Config    *schema.DNSProviderConfig `json:"config"`
	IsDefault bool                      `json:"isDefault"`
}

func (q *Queries) CreateDnsProvider(ctx context.Context, arg CreateDnsProviderParams) (DnsProvider, error) {
	row := q.queryRow(ctx, q.createDnsProviderStmt, createDnsProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsDefault,
	)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDnsProvider = `-- name: DeleteDnsProvider :exec
DELETE FROM dns_providers
WHERE
  id = ?
`

func (q *Queries) DeleteDnsProvider(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteDnsProviderStmt, deleteDnsProvider, id)
	return err
}

const getDefaultDNSProvider = `-- name: GetDefaultDNSProvider :one
SELECT
  id, name, type, config, is_default, created_at, updated_at
FROM
  dns_providers
WHERE
  is_default = TRUE
LIMIT
  1
`

func (q *Queries) GetDefaultDNSProvider(ctx context.Context) (DnsProvider, error) {
	row := q.queryRow(ctx, q.getDefaultDNSProviderStmt, getDefaultDNSProvider)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDnsProvider = `-- name: GetDnsProvider :one
SELECT
  id, name, type, config, is_default, created_at, updated_at
FROM
  dns_providers
WHERE
  id = ?
`

func (q *Queries) GetDnsProvider(ctx context.Context, id string) (DnsProvider, error) {
	row := q.queryRow(ctx, q.getDnsProviderStmt, getDnsProvider, id)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDnsProviderByName = `-- name: GetDnsProviderByName :one
SELECT
  id, name, type, config, is_default, created_at, updated_at
FROM
  dns_providers
WHERE
  name = ?
`

func (q *Queries) GetDnsProviderByName(ctx context.Context, name string) (DnsProvider, error) {
	row := q.queryRow(ctx, q.getDnsProviderByNameStmt, getDnsProviderByName, name)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDnsProviders = `-- name: ListDnsProviders :many
SELECT
  id, name, type, config, is_default, created_at, updated_at
FROM
  dns_providers
ORDER BY
  created_at DESC
LIMIT
  COALESCE(CAST(?2 AS INTEGER), -1)
OFFSET
  COALESCE(CAST(?1 AS INTEGER), 0)
`

type ListDnsProvidersParams struct {
	Offset *int64 `json:"offset"`
	Limit  *int64 `json:"limit"`
}

func (q *Queries) ListDnsProviders(ctx context.Context, arg ListDnsProvidersParams) ([]DnsProvider, error) {
	rows, err := q.query(ctx, q.listDnsProvidersStmt, listDnsProviders, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DnsProvider
	for rows.Next() {
		var i DnsProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetDefaultDNSProvider = `-- name: UnsetDefaultDNSProvider :exec
UPDATE dns_providers
SET
  is_default = FALSE
WHERE
  is_default = TRUE
`

func (q *Queries) UnsetDefaultDNSProvider(ctx context.Context) error {
	_, err := q.exec(ctx, q.unsetDefaultDNSProviderStmt, unsetDefaultDNSProvider)
	return err
}

const updateDnsProvider = `-- name: UpdateDnsProvider :one
UPDATE dns_providers
SET
  name = ?,
  type = ?,
  config = ?,
  is_default = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, name, type, config, is_default, created_at, updated_at
`

type UpdateDnsProviderParams struct {
	Name      string                    `json:"name"`
	Type      int64                     `json:"type"`
	Config    *schema.DNSProviderConfig `json:"config"`
	IsDefault bool                      `json:"isDefault"`
	ID        string                    `json:"id"`
}

func (q *Queries) UpdateDnsProvider(ctx context.Context, arg UpdateDnsProviderParams) (DnsProvider, error) {
	row := q.queryRow(ctx, q.updateDnsProviderStmt, updateDnsProvider,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsDefault,
		arg.ID,
	)
	var i DnsProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
