// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/mizuchilabs/mantrae/server/internal/store/schema"
)

type Agent struct {
	ID         string                  `json:"id"`
	ProfileID  int64                   `json:"profileId"`
	Hostname   *string                 `json:"hostname"`
	PublicIp   *string                 `json:"publicIp"`
	Containers *schema.AgentContainers `json:"containers"`
	ActiveIp   *string                 `json:"activeIp"`
	Token      string                  `json:"token"`
	CreatedAt  *time.Time              `json:"createdAt"`
	UpdatedAt  *time.Time              `json:"updatedAt"`
	PrivateIp  *string                 `json:"privateIp"`
}

type AuditLog struct {
	ID        int64      `json:"id"`
	ProfileID *int64     `json:"profileId"`
	UserID    *string    `json:"userId"`
	AgentID   *string    `json:"agentId"`
	Event     string     `json:"event"`
	Details   *string    `json:"details"`
	CreatedAt *time.Time `json:"createdAt"`
}

type DnsProvider struct {
	ID        string                    `json:"id"`
	Name      string                    `json:"name"`
	Type      int64                     `json:"type"`
	Config    *schema.DNSProviderConfig `json:"config"`
	IsDefault bool                      `json:"isDefault"`
	CreatedAt *time.Time                `json:"createdAt"`
	UpdatedAt *time.Time                `json:"updatedAt"`
}

type EntryPoint struct {
	ID        string     `json:"id"`
	ProfileID int64      `json:"profileId"`
	Name      string     `json:"name"`
	Address   *string    `json:"address"`
	IsDefault bool       `json:"isDefault"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}

type Error struct {
	ID        int64      `json:"id"`
	ProfileID int64      `json:"profileId"`
	Category  string     `json:"category"`
	Message   string     `json:"message"`
	Details   *string    `json:"details"`
	CreatedAt *time.Time `json:"createdAt"`
}

type HttpMiddleware struct {
	ID        string                 `json:"id"`
	ProfileID int64                  `json:"profileId"`
	AgentID   *string                `json:"agentId"`
	Name      string                 `json:"name"`
	Config    *schema.HTTPMiddleware `json:"config"`
	Enabled   bool                   `json:"enabled"`
	IsDefault bool                   `json:"isDefault"`
	CreatedAt *time.Time             `json:"createdAt"`
	UpdatedAt *time.Time             `json:"updatedAt"`
}

type HttpRouter struct {
	ID        string             `json:"id"`
	ProfileID int64              `json:"profileId"`
	AgentID   *string            `json:"agentId"`
	Name      string             `json:"name"`
	Config    *schema.HTTPRouter `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt *time.Time         `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt"`
}

type HttpRouterDnsProvider struct {
	HttpRouterID  string `json:"httpRouterId"`
	DnsProviderID string `json:"dnsProviderId"`
}

type HttpServersTransport struct {
	ID        string                       `json:"id"`
	ProfileID int64                        `json:"profileId"`
	AgentID   *string                      `json:"agentId"`
	Name      string                       `json:"name"`
	Config    *schema.HTTPServersTransport `json:"config"`
	Enabled   bool                         `json:"enabled"`
	CreatedAt *time.Time                   `json:"createdAt"`
	UpdatedAt *time.Time                   `json:"updatedAt"`
}

type HttpService struct {
	ID        string              `json:"id"`
	ProfileID int64               `json:"profileId"`
	AgentID   *string             `json:"agentId"`
	Name      string              `json:"name"`
	Config    *schema.HTTPService `json:"config"`
	Enabled   bool                `json:"enabled"`
	CreatedAt *time.Time          `json:"createdAt"`
	UpdatedAt *time.Time          `json:"updatedAt"`
}

type Profile struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Token       string     `json:"token"`
	CreatedAt   *time.Time `json:"createdAt"`
	UpdatedAt   *time.Time `json:"updatedAt"`
}

type Setting struct {
	Key       string     `json:"key"`
	Value     string     `json:"value"`
	UpdatedAt *time.Time `json:"updatedAt"`
}

type TcpMiddleware struct {
	ID        string                `json:"id"`
	ProfileID int64                 `json:"profileId"`
	AgentID   *string               `json:"agentId"`
	Name      string                `json:"name"`
	Config    *schema.TCPMiddleware `json:"config"`
	Enabled   bool                  `json:"enabled"`
	IsDefault bool                  `json:"isDefault"`
	CreatedAt *time.Time            `json:"createdAt"`
	UpdatedAt *time.Time            `json:"updatedAt"`
}

type TcpRouter struct {
	ID        string            `json:"id"`
	ProfileID int64             `json:"profileId"`
	AgentID   *string           `json:"agentId"`
	Name      string            `json:"name"`
	Config    *schema.TCPRouter `json:"config"`
	Enabled   bool              `json:"enabled"`
	CreatedAt *time.Time        `json:"createdAt"`
	UpdatedAt *time.Time        `json:"updatedAt"`
}

type TcpRouterDnsProvider struct {
	TcpRouterID   string `json:"tcpRouterId"`
	DnsProviderID string `json:"dnsProviderId"`
}

type TcpServersTransport struct {
	ID        string                      `json:"id"`
	ProfileID int64                       `json:"profileId"`
	AgentID   *string                     `json:"agentId"`
	Name      string                      `json:"name"`
	Config    *schema.TCPServersTransport `json:"config"`
	Enabled   bool                        `json:"enabled"`
	CreatedAt *time.Time                  `json:"createdAt"`
	UpdatedAt *time.Time                  `json:"updatedAt"`
}

type TcpService struct {
	ID        string             `json:"id"`
	ProfileID int64              `json:"profileId"`
	AgentID   *string            `json:"agentId"`
	Name      string             `json:"name"`
	Config    *schema.TCPService `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt *time.Time         `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt"`
}

type TraefikInstance struct {
	ID          string                `json:"id"`
	ProfileID   int64                 `json:"profileId"`
	Name        string                `json:"name"`
	Entrypoints *schema.EntryPoints   `json:"entrypoints"`
	Overview    *schema.Overview      `json:"overview"`
	Config      *schema.Configuration `json:"config"`
	Version     *schema.Version       `json:"version"`
	Url         string                `json:"url"`
	Username    *string               `json:"username"`
	Password    *string               `json:"password"`
	Tls         bool                  `json:"tls"`
	CreatedAt   *time.Time            `json:"createdAt"`
	UpdatedAt   *time.Time            `json:"updatedAt"`
}

type UdpRouter struct {
	ID        string            `json:"id"`
	ProfileID int64             `json:"profileId"`
	AgentID   *string           `json:"agentId"`
	Name      string            `json:"name"`
	Config    *schema.UDPRouter `json:"config"`
	Enabled   bool              `json:"enabled"`
	CreatedAt *time.Time        `json:"createdAt"`
	UpdatedAt *time.Time        `json:"updatedAt"`
}

type UdpService struct {
	ID        string             `json:"id"`
	ProfileID int64              `json:"profileId"`
	AgentID   *string            `json:"agentId"`
	Name      string             `json:"name"`
	Config    *schema.UDPService `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt *time.Time         `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt"`
}

type User struct {
	ID        string     `json:"id"`
	Username  string     `json:"username"`
	Password  string     `json:"password"`
	Email     *string    `json:"email"`
	Otp       *string    `json:"otp"`
	OtpExpiry *time.Time `json:"otpExpiry"`
	LastLogin *time.Time `json:"lastLogin"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}
