// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: udp_routers.sql

package db

import (
	"context"

	"github.com/mizuchilabs/mantrae/server/internal/store/schema"
)

const countUdpRouters = `-- name: CountUdpRouters :one
SELECT
  COUNT(*)
FROM
  udp_routers
WHERE
  profile_id = ?1
  AND (
    CAST(?2 AS TEXT) IS NULL
    OR agent_id = CAST(?2 AS TEXT)
  )
`

type CountUdpRoutersParams struct {
	ProfileID int64   `json:"profileId"`
	AgentID   *string `json:"agentId"`
}

func (q *Queries) CountUdpRouters(ctx context.Context, arg CountUdpRoutersParams) (int64, error) {
	row := q.queryRow(ctx, q.countUdpRoutersStmt, countUdpRouters, arg.ProfileID, arg.AgentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUdpRouter = `-- name: CreateUdpRouter :one
INSERT INTO
  udp_routers (
    id,
    profile_id,
    agent_id,
    name,
    config,
    created_at,
    updated_at
  )
VALUES
  (
    ?,
    ?,
    ?,
    ?,
    ?,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ) RETURNING id, profile_id, agent_id, name, config, enabled, created_at, updated_at
`

type CreateUdpRouterParams struct {
	ID        string            `json:"id"`
	ProfileID int64             `json:"profileId"`
	AgentID   *string           `json:"agentId"`
	Name      string            `json:"name"`
	Config    *schema.UDPRouter `json:"config"`
}

func (q *Queries) CreateUdpRouter(ctx context.Context, arg CreateUdpRouterParams) (UdpRouter, error) {
	row := q.queryRow(ctx, q.createUdpRouterStmt, createUdpRouter,
		arg.ID,
		arg.ProfileID,
		arg.AgentID,
		arg.Name,
		arg.Config,
	)
	var i UdpRouter
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AgentID,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUdpRouter = `-- name: DeleteUdpRouter :exec
DELETE FROM udp_routers
WHERE
  id = ?
`

func (q *Queries) DeleteUdpRouter(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.deleteUdpRouterStmt, deleteUdpRouter, id)
	return err
}

const getUdpRouter = `-- name: GetUdpRouter :one
SELECT
  id, profile_id, agent_id, name, config, enabled, created_at, updated_at
FROM
  udp_routers
WHERE
  id = ?
`

func (q *Queries) GetUdpRouter(ctx context.Context, id string) (UdpRouter, error) {
	row := q.queryRow(ctx, q.getUdpRouterStmt, getUdpRouter, id)
	var i UdpRouter
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AgentID,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUdpRoutersUsingEntryPoint = `-- name: GetUdpRoutersUsingEntryPoint :many
WITH
  ep_name AS (
    SELECT
      name
    FROM
      entry_points
    WHERE
      entry_points.id = ?
      AND entry_points.profile_id = ?
  )
SELECT
  r.id,
  r.name,
  r.config,
  r.enabled
FROM
  udp_routers r
  JOIN json_each (r.config, '$.entryPoints') je
  JOIN ep_name ep ON je.value = ep.name
`

type GetUdpRoutersUsingEntryPointParams struct {
	ID        string `json:"id"`
	ProfileID int64  `json:"profileId"`
}

type GetUdpRoutersUsingEntryPointRow struct {
	ID      string            `json:"id"`
	Name    string            `json:"name"`
	Config  *schema.UDPRouter `json:"config"`
	Enabled bool              `json:"enabled"`
}

func (q *Queries) GetUdpRoutersUsingEntryPoint(ctx context.Context, arg GetUdpRoutersUsingEntryPointParams) ([]GetUdpRoutersUsingEntryPointRow, error) {
	rows, err := q.query(ctx, q.getUdpRoutersUsingEntryPointStmt, getUdpRoutersUsingEntryPoint, arg.ID, arg.ProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUdpRoutersUsingEntryPointRow
	for rows.Next() {
		var i GetUdpRoutersUsingEntryPointRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUdpRouters = `-- name: ListUdpRouters :many
SELECT
  id, profile_id, agent_id, name, config, enabled, created_at, updated_at
FROM
  udp_routers
WHERE
  profile_id = ?1
  AND (
    CAST(?2 AS TEXT) IS NULL
    OR agent_id = CAST(?2 AS TEXT)
  )
ORDER BY
  created_at DESC
LIMIT
  COALESCE(CAST(?4 AS INTEGER), -1)
OFFSET
  COALESCE(CAST(?3 AS INTEGER), 0)
`

type ListUdpRoutersParams struct {
	ProfileID int64   `json:"profileId"`
	AgentID   *string `json:"agentId"`
	Offset    *int64  `json:"offset"`
	Limit     *int64  `json:"limit"`
}

func (q *Queries) ListUdpRouters(ctx context.Context, arg ListUdpRoutersParams) ([]UdpRouter, error) {
	rows, err := q.query(ctx, q.listUdpRoutersStmt, listUdpRouters,
		arg.ProfileID,
		arg.AgentID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UdpRouter
	for rows.Next() {
		var i UdpRouter
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.AgentID,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUdpRoutersEnabled = `-- name: ListUdpRoutersEnabled :many
SELECT
  id, profile_id, agent_id, name, config, enabled, created_at, updated_at
FROM
  udp_routers
WHERE
  profile_id = ?
  AND enabled = TRUE
`

func (q *Queries) ListUdpRoutersEnabled(ctx context.Context, profileID int64) ([]UdpRouter, error) {
	rows, err := q.query(ctx, q.listUdpRoutersEnabledStmt, listUdpRoutersEnabled, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UdpRouter
	for rows.Next() {
		var i UdpRouter
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.AgentID,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUdpRouter = `-- name: UpdateUdpRouter :one
UPDATE udp_routers
SET
  name = ?,
  config = ?,
  enabled = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, profile_id, agent_id, name, config, enabled, created_at, updated_at
`

type UpdateUdpRouterParams struct {
	Name    string            `json:"name"`
	Config  *schema.UDPRouter `json:"config"`
	Enabled bool              `json:"enabled"`
	ID      string            `json:"id"`
}

func (q *Queries) UpdateUdpRouter(ctx context.Context, arg UpdateUdpRouterParams) (UdpRouter, error) {
	row := q.queryRow(ctx, q.updateUdpRouterStmt, updateUdpRouter,
		arg.Name,
		arg.Config,
		arg.Enabled,
		arg.ID,
	)
	var i UdpRouter
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AgentID,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
