// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: http_routers.sql

package db

import (
	"context"

	"github.com/traefik/traefik/v3/pkg/config/dynamic"
)

const countHttpRouters = `-- name: CountHttpRouters :one
SELECT
  COUNT(*)
FROM
  http_routers
`

func (q *Queries) CountHttpRouters(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countHttpRoutersStmt, countHttpRouters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHttpRouter = `-- name: CreateHttpRouter :one
INSERT INTO
  http_routers (
    profile_id,
    agent_id,
    name,
    config,
    created_at,
    updated_at
  )
VALUES
  (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP) RETURNING id, profile_id, agent_id, name, config, enabled, created_at, updated_at
`

type CreateHttpRouterParams struct {
	ProfileID int64           `json:"profileId"`
	AgentID   *string         `json:"agentId"`
	Name      string          `json:"name"`
	Config    *dynamic.Router `json:"config"`
}

func (q *Queries) CreateHttpRouter(ctx context.Context, arg CreateHttpRouterParams) (HttpRouter, error) {
	row := q.queryRow(ctx, q.createHttpRouterStmt, createHttpRouter,
		arg.ProfileID,
		arg.AgentID,
		arg.Name,
		arg.Config,
	)
	var i HttpRouter
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AgentID,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHttpRouter = `-- name: DeleteHttpRouter :exec
DELETE FROM http_routers
WHERE
  id = ?
`

func (q *Queries) DeleteHttpRouter(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteHttpRouterStmt, deleteHttpRouter, id)
	return err
}

const getHttpRouter = `-- name: GetHttpRouter :one
SELECT
  id, profile_id, agent_id, name, config, enabled, created_at, updated_at
FROM
  http_routers
WHERE
  id = ?
`

func (q *Queries) GetHttpRouter(ctx context.Context, id int64) (HttpRouter, error) {
	row := q.queryRow(ctx, q.getHttpRouterStmt, getHttpRouter, id)
	var i HttpRouter
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AgentID,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHttpRoutersByProfile = `-- name: GetHttpRoutersByProfile :many
SELECT
  id, profile_id, agent_id, name, config, enabled, created_at, updated_at
FROM
  http_routers
WHERE
  profile_id = ?
`

func (q *Queries) GetHttpRoutersByProfile(ctx context.Context, profileID int64) ([]HttpRouter, error) {
	rows, err := q.query(ctx, q.getHttpRoutersByProfileStmt, getHttpRoutersByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HttpRouter
	for rows.Next() {
		var i HttpRouter
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.AgentID,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHttpRouters = `-- name: ListHttpRouters :many
SELECT
  id, profile_id, agent_id, name, config, enabled, created_at, updated_at
FROM
  http_routers
ORDER BY
  name
LIMIT
  ?
OFFSET
  ?
`

type ListHttpRoutersParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListHttpRouters(ctx context.Context, arg ListHttpRoutersParams) ([]HttpRouter, error) {
	rows, err := q.query(ctx, q.listHttpRoutersStmt, listHttpRouters, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HttpRouter
	for rows.Next() {
		var i HttpRouter
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.AgentID,
			&i.Name,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHttpRouter = `-- name: UpdateHttpRouter :one
UPDATE http_routers
SET
  name = ?,
  config = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, profile_id, agent_id, name, config, enabled, created_at, updated_at
`

type UpdateHttpRouterParams struct {
	Name   string          `json:"name"`
	Config *dynamic.Router `json:"config"`
	ID     int64           `json:"id"`
}

func (q *Queries) UpdateHttpRouter(ctx context.Context, arg UpdateHttpRouterParams) (HttpRouter, error) {
	row := q.queryRow(ctx, q.updateHttpRouterStmt, updateHttpRouter, arg.Name, arg.Config, arg.ID)
	var i HttpRouter
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AgentID,
		&i.Name,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
