// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"

	"github.com/mizuchilabs/mantrae/internal/store/schema"
)

type Agent struct {
	ID         string                  `json:"id"`
	ProfileID  int64                   `json:"profileId"`
	Hostname   *string                 `json:"hostname"`
	PublicIp   *string                 `json:"publicIp"`
	Containers *schema.AgentContainers `json:"containers"`
	ActiveIp   *string                 `json:"activeIp"`
	Token      string                  `json:"token"`
	CreatedAt  *time.Time              `json:"createdAt"`
	UpdatedAt  *time.Time              `json:"updatedAt"`
	PrivateIp  *string                 `json:"privateIp"`
}

type AuditLog struct {
	ID        int64      `json:"id"`
	ProfileID *int64     `json:"profileId"`
	UserID    *string    `json:"userId"`
	AgentID   *string    `json:"agentId"`
	Event     string     `json:"event"`
	Details   *string    `json:"details"`
	CreatedAt *time.Time `json:"createdAt"`
}

type DnsProvider struct {
	ID        int64                     `json:"id"`
	Name      string                    `json:"name"`
	Type      string                    `json:"type"`
	Config    *schema.DNSProviderConfig `json:"config"`
	IsActive  bool                      `json:"isActive"`
	CreatedAt *time.Time                `json:"createdAt"`
	UpdatedAt *time.Time                `json:"updatedAt"`
}

type EntryPoint struct {
	ID        int64      `json:"id"`
	ProfileID int64      `json:"profileId"`
	Name      string     `json:"name"`
	Address   string     `json:"address"`
	IsDefault bool       `json:"isDefault"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}

type Error struct {
	ID        int64      `json:"id"`
	ProfileID int64      `json:"profileId"`
	Category  string     `json:"category"`
	Message   string     `json:"message"`
	Details   *string    `json:"details"`
	CreatedAt *time.Time `json:"createdAt"`
}

type HttpMiddleware struct {
	ID        int64              `json:"id"`
	ProfileID int64              `json:"profileId"`
	AgentID   *string            `json:"agentId"`
	Name      string             `json:"name"`
	Config    *schema.Middleware `json:"config"`
	Enabled   bool               `json:"enabled"`
	CreatedAt *time.Time         `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt"`
}

type HttpRouter struct {
	ID        int64          `json:"id"`
	ProfileID int64          `json:"profileId"`
	AgentID   *string        `json:"agentId"`
	Name      string         `json:"name"`
	Config    *schema.Router `json:"config"`
	Enabled   bool           `json:"enabled"`
	CreatedAt *time.Time     `json:"createdAt"`
	UpdatedAt *time.Time     `json:"updatedAt"`
}

type HttpRouterDnsProvider struct {
	HttpRouterID  int64 `json:"httpRouterId"`
	DnsProviderID int64 `json:"dnsProviderId"`
}

type HttpService struct {
	ID        int64           `json:"id"`
	ProfileID int64           `json:"profileId"`
	AgentID   *string         `json:"agentId"`
	Name      string          `json:"name"`
	Config    *schema.Service `json:"config"`
	CreatedAt *time.Time      `json:"createdAt"`
	UpdatedAt *time.Time      `json:"updatedAt"`
}

type Profile struct {
	ID          int64      `json:"id"`
	Name        string     `json:"name"`
	CreatedAt   *time.Time `json:"createdAt"`
	UpdatedAt   *time.Time `json:"updatedAt"`
	Description *string    `json:"description"`
}

type Setting struct {
	Key       string     `json:"key"`
	Value     string     `json:"value"`
	UpdatedAt *time.Time `json:"updatedAt"`
}

type TcpMiddleware struct {
	ID        int64                 `json:"id"`
	ProfileID int64                 `json:"profileId"`
	AgentID   *string               `json:"agentId"`
	Name      string                `json:"name"`
	Config    *schema.TCPMiddleware `json:"config"`
	Enabled   bool                  `json:"enabled"`
	CreatedAt *time.Time            `json:"createdAt"`
	UpdatedAt *time.Time            `json:"updatedAt"`
}

type TcpRouter struct {
	ID        int64             `json:"id"`
	ProfileID int64             `json:"profileId"`
	AgentID   *string           `json:"agentId"`
	Name      string            `json:"name"`
	Config    *schema.TCPRouter `json:"config"`
	Enabled   bool              `json:"enabled"`
	CreatedAt *time.Time        `json:"createdAt"`
	UpdatedAt *time.Time        `json:"updatedAt"`
}

type TcpRouterDnsProvider struct {
	TcpRouterID   int64 `json:"tcpRouterId"`
	DnsProviderID int64 `json:"dnsProviderId"`
}

type TcpService struct {
	ID        int64              `json:"id"`
	ProfileID int64              `json:"profileId"`
	AgentID   *string            `json:"agentId"`
	Name      string             `json:"name"`
	Config    *schema.TCPService `json:"config"`
	CreatedAt *time.Time         `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt"`
}

type TraefikInstance struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profileId"`
	Entrypoints *schema.EntryPoints   `json:"entrypoints"`
	Overview    *schema.Overview      `json:"overview"`
	Config      *schema.Configuration `json:"config"`
	Version     *string               `json:"version"`
	Url         string                `json:"url"`
	Username    *string               `json:"username"`
	Password    *string               `json:"password"`
	Tls         bool                  `json:"tls"`
	CreatedAt   *time.Time            `json:"createdAt"`
	UpdatedAt   *time.Time            `json:"updatedAt"`
}

type UdpRouter struct {
	ID        int64             `json:"id"`
	ProfileID int64             `json:"profileId"`
	AgentID   *string           `json:"agentId"`
	Name      string            `json:"name"`
	Config    *schema.UDPRouter `json:"config"`
	Enabled   bool              `json:"enabled"`
	CreatedAt *time.Time        `json:"createdAt"`
	UpdatedAt *time.Time        `json:"updatedAt"`
}

type UdpService struct {
	ID        int64              `json:"id"`
	ProfileID int64              `json:"profileId"`
	AgentID   *string            `json:"agentId"`
	Name      string             `json:"name"`
	Config    *schema.UDPService `json:"config"`
	CreatedAt *time.Time         `json:"createdAt"`
	UpdatedAt *time.Time         `json:"updatedAt"`
}

type User struct {
	ID        string     `json:"id"`
	Username  string     `json:"username"`
	Password  string     `json:"password"`
	Email     *string    `json:"email"`
	IsAdmin   bool       `json:"isAdmin"`
	Otp       *string    `json:"otp"`
	OtpExpiry *time.Time `json:"otpExpiry"`
	LastLogin *time.Time `json:"lastLogin"`
	CreatedAt *time.Time `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt"`
}
