// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CountAgents(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountDnsProviders(ctx context.Context) (int64, error)
	CountEntryPoints(ctx context.Context) (int64, error)
	CountHttpMiddlewares(ctx context.Context) (int64, error)
	CountHttpMiddlewaresByAgent(ctx context.Context, agentID *string) (int64, error)
	CountHttpMiddlewaresByProfile(ctx context.Context, profileID int64) (int64, error)
	CountHttpRouters(ctx context.Context) (int64, error)
	CountHttpRoutersByAgent(ctx context.Context, agentID *string) (int64, error)
	CountHttpRoutersByProfile(ctx context.Context, profileID int64) (int64, error)
	CountHttpServersTransports(ctx context.Context) (int64, error)
	CountHttpServersTransportsByAgent(ctx context.Context, agentID *string) (int64, error)
	CountHttpServersTransportsByProfile(ctx context.Context, profileID int64) (int64, error)
	CountHttpServices(ctx context.Context) (int64, error)
	CountHttpServicesByAgent(ctx context.Context, agentID *string) (int64, error)
	CountHttpServicesByProfile(ctx context.Context, profileID int64) (int64, error)
	CountMiddlewaresByAgent(ctx context.Context, arg CountMiddlewaresByAgentParams) (int64, error)
	CountMiddlewaresByProfile(ctx context.Context, arg CountMiddlewaresByProfileParams) (int64, error)
	CountProfiles(ctx context.Context) (int64, error)
	CountRoutersByAgent(ctx context.Context, arg CountRoutersByAgentParams) (int64, error)
	CountRoutersByProfile(ctx context.Context, arg CountRoutersByProfileParams) (int64, error)
	CountServersTransportsByAgent(ctx context.Context, arg CountServersTransportsByAgentParams) (int64, error)
	CountServersTransportsByProfile(ctx context.Context, arg CountServersTransportsByProfileParams) (int64, error)
	CountServicesByAgent(ctx context.Context, arg CountServicesByAgentParams) (int64, error)
	CountServicesByProfile(ctx context.Context, arg CountServicesByProfileParams) (int64, error)
	CountTcpMiddlewares(ctx context.Context) (int64, error)
	CountTcpMiddlewaresByAgent(ctx context.Context, agentID *string) (int64, error)
	CountTcpMiddlewaresByProfile(ctx context.Context, profileID int64) (int64, error)
	CountTcpRouters(ctx context.Context) (int64, error)
	CountTcpRoutersByAgent(ctx context.Context, agentID *string) (int64, error)
	CountTcpRoutersByProfile(ctx context.Context, profileID int64) (int64, error)
	CountTcpServersTransports(ctx context.Context) (int64, error)
	CountTcpServersTransportsByAgent(ctx context.Context, agentID *string) (int64, error)
	CountTcpServersTransportsByProfile(ctx context.Context, profileID int64) (int64, error)
	CountTcpServices(ctx context.Context) (int64, error)
	CountTcpServicesByAgent(ctx context.Context, agentID *string) (int64, error)
	CountTcpServicesByProfile(ctx context.Context, profileID int64) (int64, error)
	CountTraefikInstances(ctx context.Context) (int64, error)
	CountUdpRouters(ctx context.Context) (int64, error)
	CountUdpRoutersByAgent(ctx context.Context, agentID *string) (int64, error)
	CountUdpRoutersByProfile(ctx context.Context, profileID int64) (int64, error)
	CountUdpServices(ctx context.Context) (int64, error)
	CountUdpServicesByAgent(ctx context.Context, agentID *string) (int64, error)
	CountUdpServicesByProfile(ctx context.Context, profileID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateDnsProvider(ctx context.Context, arg CreateDnsProviderParams) (DnsProvider, error)
	CreateEntryPoint(ctx context.Context, arg CreateEntryPointParams) (EntryPoint, error)
	CreateHttpMiddleware(ctx context.Context, arg CreateHttpMiddlewareParams) (HttpMiddleware, error)
	CreateHttpRouter(ctx context.Context, arg CreateHttpRouterParams) (HttpRouter, error)
	CreateHttpRouterDNSProvider(ctx context.Context, arg CreateHttpRouterDNSProviderParams) error
	CreateHttpServersTransport(ctx context.Context, arg CreateHttpServersTransportParams) (HttpServersTransport, error)
	CreateHttpService(ctx context.Context, arg CreateHttpServiceParams) (HttpService, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateTcpMiddleware(ctx context.Context, arg CreateTcpMiddlewareParams) (TcpMiddleware, error)
	CreateTcpRouter(ctx context.Context, arg CreateTcpRouterParams) (TcpRouter, error)
	CreateTcpRouterDNSProvider(ctx context.Context, arg CreateTcpRouterDNSProviderParams) error
	CreateTcpServersTransport(ctx context.Context, arg CreateTcpServersTransportParams) (TcpServersTransport, error)
	CreateTcpService(ctx context.Context, arg CreateTcpServiceParams) (TcpService, error)
	CreateUdpRouter(ctx context.Context, arg CreateUdpRouterParams) (UdpRouter, error)
	CreateUdpService(ctx context.Context, arg CreateUdpServiceParams) (UdpService, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteDnsProvider(ctx context.Context, id int64) error
	DeleteEntryPointByID(ctx context.Context, id int64) error
	DeleteErrorById(ctx context.Context, id int64) error
	DeleteErrorsByProfile(ctx context.Context, profileID int64) error
	DeleteErrorsByProfileCategory(ctx context.Context, arg DeleteErrorsByProfileCategoryParams) error
	DeleteHttpMiddleware(ctx context.Context, id int64) error
	DeleteHttpRouter(ctx context.Context, id int64) error
	DeleteHttpRouterDNSProvider(ctx context.Context, arg DeleteHttpRouterDNSProviderParams) error
	DeleteHttpServersTransport(ctx context.Context, id int64) error
	DeleteHttpService(ctx context.Context, id int64) error
	DeleteOldAuditLogs(ctx context.Context) error
	DeleteProfile(ctx context.Context, id int64) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTcpMiddleware(ctx context.Context, id int64) error
	DeleteTcpRouter(ctx context.Context, id int64) error
	DeleteTcpRouterDNSProvider(ctx context.Context, arg DeleteTcpRouterDNSProviderParams) error
	DeleteTcpServersTransport(ctx context.Context, id int64) error
	DeleteTcpService(ctx context.Context, id int64) error
	DeleteTraefikInstanceByID(ctx context.Context, id int64) error
	DeleteUdpRouter(ctx context.Context, id int64) error
	DeleteUdpService(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id string) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetDefaultDNSProvider(ctx context.Context) (DnsProvider, error)
	GetDefaultEntryPoint(ctx context.Context) (EntryPoint, error)
	GetDnsProvider(ctx context.Context, id int64) (DnsProvider, error)
	GetDnsProviderByName(ctx context.Context, name string) (DnsProvider, error)
	GetDnsProvidersByHttpRouter(ctx context.Context, httpRouterID int64) ([]DnsProvider, error)
	GetDnsProvidersByTcpRouter(ctx context.Context, tcpRouterID int64) ([]DnsProvider, error)
	GetEntryPoint(ctx context.Context, id int64) (EntryPoint, error)
	GetErrorsByProfile(ctx context.Context, profileID int64) ([]Error, error)
	GetHttpMiddleware(ctx context.Context, id int64) (HttpMiddleware, error)
	GetHttpRouter(ctx context.Context, id int64) (HttpRouter, error)
	GetHttpRouterDomains(ctx context.Context) ([]GetHttpRouterDomainsRow, error)
	GetHttpRoutersUsingEntryPoint(ctx context.Context, arg GetHttpRoutersUsingEntryPointParams) ([]GetHttpRoutersUsingEntryPointRow, error)
	GetHttpRoutersUsingMiddleware(ctx context.Context, arg GetHttpRoutersUsingMiddlewareParams) ([]GetHttpRoutersUsingMiddlewareRow, error)
	GetHttpServersTransport(ctx context.Context, id int64) (HttpServersTransport, error)
	GetHttpService(ctx context.Context, id int64) (HttpService, error)
	GetHttpServiceByName(ctx context.Context, name string) (HttpService, error)
	GetProfile(ctx context.Context, id int64) (Profile, error)
	GetProfileByName(ctx context.Context, name string) (Profile, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetTcpMiddleware(ctx context.Context, id int64) (TcpMiddleware, error)
	GetTcpRouter(ctx context.Context, id int64) (TcpRouter, error)
	GetTcpRouterDomains(ctx context.Context) ([]GetTcpRouterDomainsRow, error)
	GetTcpRoutersUsingEntryPoint(ctx context.Context, arg GetTcpRoutersUsingEntryPointParams) ([]GetTcpRoutersUsingEntryPointRow, error)
	GetTcpRoutersUsingMiddleware(ctx context.Context, arg GetTcpRoutersUsingMiddlewareParams) ([]GetTcpRoutersUsingMiddlewareRow, error)
	GetTcpServersTransport(ctx context.Context, id int64) (TcpServersTransport, error)
	GetTcpService(ctx context.Context, id int64) (TcpService, error)
	GetTcpServiceByName(ctx context.Context, name string) (TcpService, error)
	GetTraefikInstanceByID(ctx context.Context, id int64) (TraefikInstance, error)
	GetTraefikInstanceByName(ctx context.Context, name string) (TraefikInstance, error)
	GetUdpRouter(ctx context.Context, id int64) (UdpRouter, error)
	GetUdpRoutersUsingEntryPoint(ctx context.Context, arg GetUdpRoutersUsingEntryPointParams) ([]GetUdpRoutersUsingEntryPointRow, error)
	GetUdpService(ctx context.Context, id int64) (UdpService, error)
	GetUdpServiceByName(ctx context.Context, name string) (UdpService, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]User, error)
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error)
	ListDnsProviders(ctx context.Context, arg ListDnsProvidersParams) ([]DnsProvider, error)
	ListEntryPoints(ctx context.Context, arg ListEntryPointsParams) ([]EntryPoint, error)
	ListErrors(ctx context.Context) ([]Error, error)
	ListHttpMiddlewares(ctx context.Context, arg ListHttpMiddlewaresParams) ([]HttpMiddleware, error)
	ListHttpMiddlewaresByAgent(ctx context.Context, arg ListHttpMiddlewaresByAgentParams) ([]HttpMiddleware, error)
	ListHttpMiddlewaresEnabled(ctx context.Context, arg ListHttpMiddlewaresEnabledParams) ([]HttpMiddleware, error)
	ListHttpRouters(ctx context.Context, arg ListHttpRoutersParams) ([]HttpRouter, error)
	ListHttpRoutersByAgent(ctx context.Context, arg ListHttpRoutersByAgentParams) ([]HttpRouter, error)
	ListHttpRoutersEnabled(ctx context.Context, arg ListHttpRoutersEnabledParams) ([]HttpRouter, error)
	ListHttpServersTransports(ctx context.Context, arg ListHttpServersTransportsParams) ([]HttpServersTransport, error)
	ListHttpServersTransportsByAgent(ctx context.Context, arg ListHttpServersTransportsByAgentParams) ([]HttpServersTransport, error)
	ListHttpServersTransportsEnabled(ctx context.Context, arg ListHttpServersTransportsEnabledParams) ([]HttpServersTransport, error)
	ListHttpServices(ctx context.Context, arg ListHttpServicesParams) ([]HttpService, error)
	ListHttpServicesByAgent(ctx context.Context, arg ListHttpServicesByAgentParams) ([]HttpService, error)
	ListHttpServicesEnabled(ctx context.Context, arg ListHttpServicesEnabledParams) ([]HttpService, error)
	ListMiddlewaresByAgent(ctx context.Context, arg ListMiddlewaresByAgentParams) ([]ListMiddlewaresByAgentRow, error)
	ListMiddlewaresByProfile(ctx context.Context, arg ListMiddlewaresByProfileParams) ([]ListMiddlewaresByProfileRow, error)
	ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error)
	ListRoutersByAgent(ctx context.Context, arg ListRoutersByAgentParams) ([]ListRoutersByAgentRow, error)
	ListRoutersByProfile(ctx context.Context, arg ListRoutersByProfileParams) ([]ListRoutersByProfileRow, error)
	ListServersTransportsByAgent(ctx context.Context, arg ListServersTransportsByAgentParams) ([]ListServersTransportsByAgentRow, error)
	ListServersTransportsByProfile(ctx context.Context, arg ListServersTransportsByProfileParams) ([]ListServersTransportsByProfileRow, error)
	ListServicesByAgent(ctx context.Context, arg ListServicesByAgentParams) ([]ListServicesByAgentRow, error)
	ListServicesByProfile(ctx context.Context, arg ListServicesByProfileParams) ([]ListServicesByProfileRow, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListTcpMiddlewares(ctx context.Context, arg ListTcpMiddlewaresParams) ([]TcpMiddleware, error)
	ListTcpMiddlewaresByAgent(ctx context.Context, arg ListTcpMiddlewaresByAgentParams) ([]TcpMiddleware, error)
	ListTcpMiddlewaresEnabled(ctx context.Context, arg ListTcpMiddlewaresEnabledParams) ([]TcpMiddleware, error)
	ListTcpRouters(ctx context.Context, arg ListTcpRoutersParams) ([]TcpRouter, error)
	ListTcpRoutersByAgent(ctx context.Context, arg ListTcpRoutersByAgentParams) ([]TcpRouter, error)
	ListTcpRoutersEnabled(ctx context.Context, arg ListTcpRoutersEnabledParams) ([]TcpRouter, error)
	ListTcpServersTransports(ctx context.Context, arg ListTcpServersTransportsParams) ([]TcpServersTransport, error)
	ListTcpServersTransportsByAgent(ctx context.Context, arg ListTcpServersTransportsByAgentParams) ([]TcpServersTransport, error)
	ListTcpServersTransportsEnabled(ctx context.Context, arg ListTcpServersTransportsEnabledParams) ([]TcpServersTransport, error)
	ListTcpServices(ctx context.Context, arg ListTcpServicesParams) ([]TcpService, error)
	ListTcpServicesByAgent(ctx context.Context, arg ListTcpServicesByAgentParams) ([]TcpService, error)
	ListTcpServicesEnabled(ctx context.Context, arg ListTcpServicesEnabledParams) ([]TcpService, error)
	ListTraefikInstances(ctx context.Context, arg ListTraefikInstancesParams) ([]TraefikInstance, error)
	ListUdpRouters(ctx context.Context, arg ListUdpRoutersParams) ([]UdpRouter, error)
	ListUdpRoutersByAgent(ctx context.Context, arg ListUdpRoutersByAgentParams) ([]UdpRouter, error)
	ListUdpRoutersEnabled(ctx context.Context, arg ListUdpRoutersEnabledParams) ([]UdpRouter, error)
	ListUdpServices(ctx context.Context, arg ListUdpServicesParams) ([]UdpService, error)
	ListUdpServicesByAgent(ctx context.Context, arg ListUdpServicesByAgentParams) ([]UdpService, error)
	ListUdpServicesEnabled(ctx context.Context, arg ListUdpServicesEnabledParams) ([]UdpService, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogError(ctx context.Context, arg LogErrorParams) error
	PurgeTraefikInstances(ctx context.Context) error
	UnsetDefaultDNSProvider(ctx context.Context) error
	UnsetDefaultEntryPoint(ctx context.Context) error
	UnsetDefaultHttpMiddleware(ctx context.Context) error
	UnsetDefaultTcpMiddleware(ctx context.Context) error
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateAgentIP(ctx context.Context, arg UpdateAgentIPParams) error
	UpdateAgentToken(ctx context.Context, arg UpdateAgentTokenParams) error
	UpdateDnsProvider(ctx context.Context, arg UpdateDnsProviderParams) (DnsProvider, error)
	UpdateEntryPoint(ctx context.Context, arg UpdateEntryPointParams) (EntryPoint, error)
	UpdateHttpMiddleware(ctx context.Context, arg UpdateHttpMiddlewareParams) (HttpMiddleware, error)
	UpdateHttpRouter(ctx context.Context, arg UpdateHttpRouterParams) (HttpRouter, error)
	UpdateHttpServersTransport(ctx context.Context, arg UpdateHttpServersTransportParams) (HttpServersTransport, error)
	UpdateHttpService(ctx context.Context, arg UpdateHttpServiceParams) (HttpService, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateTcpMiddleware(ctx context.Context, arg UpdateTcpMiddlewareParams) (TcpMiddleware, error)
	UpdateTcpRouter(ctx context.Context, arg UpdateTcpRouterParams) (TcpRouter, error)
	UpdateTcpServersTransport(ctx context.Context, arg UpdateTcpServersTransportParams) (TcpServersTransport, error)
	UpdateTcpService(ctx context.Context, arg UpdateTcpServiceParams) (TcpService, error)
	UpdateUdpRouter(ctx context.Context, arg UpdateUdpRouterParams) (UdpRouter, error)
	UpdateUdpService(ctx context.Context, arg UpdateUdpServiceParams) (UdpService, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
	UpsertTraefikInstance(ctx context.Context, arg UpsertTraefikInstanceParams) (TraefikInstance, error)
}

var _ Querier = (*Queries)(nil)
