// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CountAgents(ctx context.Context) (int64, error)
	CountDnsProviders(ctx context.Context) (int64, error)
	CountEntryPoints(ctx context.Context) (int64, error)
	CountHttpMiddlewares(ctx context.Context) (int64, error)
	CountHttpRouters(ctx context.Context) (int64, error)
	CountHttpServices(ctx context.Context) (int64, error)
	CountProfiles(ctx context.Context) (int64, error)
	CountTcpMiddlewares(ctx context.Context) (int64, error)
	CountTcpRouters(ctx context.Context) (int64, error)
	CountTcpServices(ctx context.Context) (int64, error)
	CountTraefikInstances(ctx context.Context) (int64, error)
	CountUdpRouters(ctx context.Context) (int64, error)
	CountUdpServices(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateDnsProvider(ctx context.Context, arg CreateDnsProviderParams) (DnsProvider, error)
	CreateEntryPoint(ctx context.Context, arg CreateEntryPointParams) (EntryPoint, error)
	CreateHttpMiddleware(ctx context.Context, arg CreateHttpMiddlewareParams) (HttpMiddleware, error)
	CreateHttpRouter(ctx context.Context, arg CreateHttpRouterParams) (HttpRouter, error)
	CreateHttpRouterDNSProvider(ctx context.Context, arg CreateHttpRouterDNSProviderParams) error
	CreateHttpService(ctx context.Context, arg CreateHttpServiceParams) (HttpService, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateTcpMiddleware(ctx context.Context, arg CreateTcpMiddlewareParams) (TcpMiddleware, error)
	CreateTcpRouter(ctx context.Context, arg CreateTcpRouterParams) (TcpRouter, error)
	CreateTcpRouterDNSProvider(ctx context.Context, arg CreateTcpRouterDNSProviderParams) error
	CreateTcpService(ctx context.Context, arg CreateTcpServiceParams) (TcpService, error)
	CreateTraefikInstance(ctx context.Context, arg CreateTraefikInstanceParams) (TraefikInstance, error)
	CreateUdpRouter(ctx context.Context, arg CreateUdpRouterParams) (UdpRouter, error)
	CreateUdpRouterDNSProvider(ctx context.Context, arg CreateUdpRouterDNSProviderParams) error
	CreateUdpService(ctx context.Context, arg CreateUdpServiceParams) (UdpService, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAgent(ctx context.Context, id string) error
	DeleteDnsProvider(ctx context.Context, id int64) error
	DeleteEntryPoint(ctx context.Context, id int64) error
	DeleteErrorById(ctx context.Context, id int64) error
	DeleteErrorsByProfile(ctx context.Context, profileID int64) error
	DeleteErrorsByProfileCategory(ctx context.Context, arg DeleteErrorsByProfileCategoryParams) error
	DeleteHttpMiddleware(ctx context.Context, id int64) error
	DeleteHttpRouter(ctx context.Context, id int64) error
	DeleteHttpRouterDNSProvider(ctx context.Context, arg DeleteHttpRouterDNSProviderParams) error
	DeleteHttpService(ctx context.Context, id int64) error
	DeleteProfile(ctx context.Context, id int64) error
	DeleteSetting(ctx context.Context, key string) error
	DeleteTcpMiddleware(ctx context.Context, id int64) error
	DeleteTcpRouter(ctx context.Context, id int64) error
	DeleteTcpRouterDNSProvider(ctx context.Context, arg DeleteTcpRouterDNSProviderParams) error
	DeleteTcpService(ctx context.Context, id int64) error
	DeleteTraefikInstance(ctx context.Context, id int64) error
	DeleteUdpRouter(ctx context.Context, id int64) error
	DeleteUdpRouterDNSProvider(ctx context.Context, arg DeleteUdpRouterDNSProviderParams) error
	DeleteUdpService(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id string) error
	GetAgent(ctx context.Context, id string) (Agent, error)
	GetDnsProvider(ctx context.Context, id int64) (DnsProvider, error)
	GetDnsProviderByName(ctx context.Context, name string) (DnsProvider, error)
	GetEntryPoint(ctx context.Context, id int64) (EntryPoint, error)
	GetErrorsByProfile(ctx context.Context, profileID int64) ([]Error, error)
	GetHttpMiddleware(ctx context.Context, id int64) (HttpMiddleware, error)
	GetHttpMiddlewaresByProfile(ctx context.Context, profileID int64) ([]HttpMiddleware, error)
	GetHttpRouter(ctx context.Context, id int64) (HttpRouter, error)
	GetHttpRouterDNSProvider(ctx context.Context, arg GetHttpRouterDNSProviderParams) (HttpRouterDnsProvider, error)
	GetHttpRoutersByProfile(ctx context.Context, profileID int64) ([]HttpRouter, error)
	GetHttpService(ctx context.Context, id int64) (HttpService, error)
	GetHttpServicesByProfile(ctx context.Context, profileID int64) ([]HttpService, error)
	GetProfile(ctx context.Context, id int64) (Profile, error)
	GetProfileByName(ctx context.Context, name string) (Profile, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetTcpMiddleware(ctx context.Context, id int64) (TcpMiddleware, error)
	GetTcpMiddlewaresByProfile(ctx context.Context, profileID int64) ([]TcpMiddleware, error)
	GetTcpRouter(ctx context.Context, id int64) (TcpRouter, error)
	GetTcpRouterDNSProvider(ctx context.Context, arg GetTcpRouterDNSProviderParams) (TcpRouterDnsProvider, error)
	GetTcpRoutersByProfile(ctx context.Context, profileID int64) ([]TcpRouter, error)
	GetTcpService(ctx context.Context, id int64) (TcpService, error)
	GetTcpServicesByProfile(ctx context.Context, profileID int64) ([]TcpService, error)
	GetTraefikInstance(ctx context.Context, id int64) (TraefikInstance, error)
	GetTraefikInstanceByProfile(ctx context.Context, profileID int64) (TraefikInstance, error)
	GetUdpRouter(ctx context.Context, id int64) (UdpRouter, error)
	GetUdpRouterDNSProvider(ctx context.Context, arg GetUdpRouterDNSProviderParams) (UdpRouterDnsProvider, error)
	GetUdpRoutersByProfile(ctx context.Context, profileID int64) ([]UdpRouter, error)
	GetUdpService(ctx context.Context, id int64) (UdpService, error)
	GetUdpServicesByProfile(ctx context.Context, profileID int64) ([]UdpService, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAdminUsers(ctx context.Context, arg ListAdminUsersParams) ([]User, error)
	ListAgents(ctx context.Context, arg ListAgentsParams) ([]Agent, error)
	ListDnsProviders(ctx context.Context, arg ListDnsProvidersParams) ([]DnsProvider, error)
	ListEntryPoints(ctx context.Context, arg ListEntryPointsParams) ([]EntryPoint, error)
	ListErrors(ctx context.Context) ([]Error, error)
	ListHttpMiddlewares(ctx context.Context, arg ListHttpMiddlewaresParams) ([]HttpMiddleware, error)
	ListHttpRouterDNSProviders(ctx context.Context, httpRouterID int64) ([]HttpRouterDnsProvider, error)
	ListHttpRouters(ctx context.Context, arg ListHttpRoutersParams) ([]HttpRouter, error)
	ListHttpServices(ctx context.Context, arg ListHttpServicesParams) ([]HttpService, error)
	ListProfiles(ctx context.Context, arg ListProfilesParams) ([]Profile, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListTcpMiddlewares(ctx context.Context, arg ListTcpMiddlewaresParams) ([]TcpMiddleware, error)
	ListTcpRouterDNSProviders(ctx context.Context, tcpRouterID int64) ([]TcpRouterDnsProvider, error)
	ListTcpRouters(ctx context.Context, arg ListTcpRoutersParams) ([]TcpRouter, error)
	ListTcpServices(ctx context.Context, arg ListTcpServicesParams) ([]TcpService, error)
	ListTraefikInstances(ctx context.Context) ([]TraefikInstance, error)
	ListUdpRouterDNSProvider(ctx context.Context, udpRouterID int64) ([]UdpRouterDnsProvider, error)
	ListUdpRouters(ctx context.Context, arg ListUdpRoutersParams) ([]UdpRouter, error)
	ListUdpServices(ctx context.Context, arg ListUdpServicesParams) ([]UdpService, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	LogError(ctx context.Context, arg LogErrorParams) error
	UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error)
	UpdateAgentIP(ctx context.Context, arg UpdateAgentIPParams) error
	UpdateAgentToken(ctx context.Context, arg UpdateAgentTokenParams) error
	UpdateDnsProvider(ctx context.Context, arg UpdateDnsProviderParams) (DnsProvider, error)
	UpdateEntryPoint(ctx context.Context, arg UpdateEntryPointParams) (EntryPoint, error)
	UpdateHttpMiddleware(ctx context.Context, arg UpdateHttpMiddlewareParams) (HttpMiddleware, error)
	UpdateHttpRouter(ctx context.Context, arg UpdateHttpRouterParams) (HttpRouter, error)
	UpdateHttpService(ctx context.Context, arg UpdateHttpServiceParams) (HttpService, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error)
	UpdateTcpMiddleware(ctx context.Context, arg UpdateTcpMiddlewareParams) (TcpMiddleware, error)
	UpdateTcpRouter(ctx context.Context, arg UpdateTcpRouterParams) (TcpRouter, error)
	UpdateTcpService(ctx context.Context, arg UpdateTcpServiceParams) (TcpService, error)
	UpdateTraefikInstance(ctx context.Context, arg UpdateTraefikInstanceParams) (TraefikInstance, error)
	UpdateUdpRouter(ctx context.Context, arg UpdateUdpRouterParams) (UdpRouter, error)
	UpdateUdpService(ctx context.Context, arg UpdateUdpServiceParams) (UdpService, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id string) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserResetToken(ctx context.Context, arg UpdateUserResetTokenParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
