// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: traefik_instances.sql

package db

import (
	"context"

	"github.com/mizuchilabs/mantrae/internal/store/schema"
)

const countTraefikInstances = `-- name: CountTraefikInstances :one
SELECT
  COUNT(*)
FROM
  traefik_instances
`

func (q *Queries) CountTraefikInstances(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countTraefikInstancesStmt, countTraefikInstances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTraefikInstance = `-- name: CreateTraefikInstance :one
INSERT INTO
  traefik_instances (
    id,
    profile_id,
    entrypoints,
    overview,
    config,
    version,
    created_at,
    updated_at
  )
VALUES
  (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
  ) RETURNING id, profile_id, entrypoints, overview, config, version, created_at, updated_at
`

type CreateTraefikInstanceParams struct {
	ID          int64                 `json:"id"`
	ProfileID   int64                 `json:"profileId"`
	Entrypoints *schema.EntryPoint    `json:"entrypoints"`
	Overview    *schema.Overview      `json:"overview"`
	Config      *schema.Configuration `json:"config"`
	Version     *string               `json:"version"`
}

func (q *Queries) CreateTraefikInstance(ctx context.Context, arg CreateTraefikInstanceParams) (TraefikInstance, error) {
	row := q.queryRow(ctx, q.createTraefikInstanceStmt, createTraefikInstance,
		arg.ID,
		arg.ProfileID,
		arg.Entrypoints,
		arg.Overview,
		arg.Config,
		arg.Version,
	)
	var i TraefikInstance
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Entrypoints,
		&i.Overview,
		&i.Config,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTraefikInstance = `-- name: DeleteTraefikInstance :exec
DELETE FROM traefik_instances
WHERE
  id = ?
`

func (q *Queries) DeleteTraefikInstance(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteTraefikInstanceStmt, deleteTraefikInstance, id)
	return err
}

const getTraefikInstance = `-- name: GetTraefikInstance :one
SELECT
  id, profile_id, entrypoints, overview, config, version, created_at, updated_at
FROM
  traefik_instances
WHERE
  id = ?
`

func (q *Queries) GetTraefikInstance(ctx context.Context, id int64) (TraefikInstance, error) {
	row := q.queryRow(ctx, q.getTraefikInstanceStmt, getTraefikInstance, id)
	var i TraefikInstance
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Entrypoints,
		&i.Overview,
		&i.Config,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTraefikInstanceByProfile = `-- name: GetTraefikInstanceByProfile :one
SELECT
  id, profile_id, entrypoints, overview, config, version, created_at, updated_at
FROM
  traefik_instances
WHERE
  profile_id = ?
`

func (q *Queries) GetTraefikInstanceByProfile(ctx context.Context, profileID int64) (TraefikInstance, error) {
	row := q.queryRow(ctx, q.getTraefikInstanceByProfileStmt, getTraefikInstanceByProfile, profileID)
	var i TraefikInstance
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Entrypoints,
		&i.Overview,
		&i.Config,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTraefikInstances = `-- name: ListTraefikInstances :many
SELECT
  id, profile_id, entrypoints, overview, config, version, created_at, updated_at
FROM
  traefik_instances
ORDER BY
  created_at DESC
`

func (q *Queries) ListTraefikInstances(ctx context.Context) ([]TraefikInstance, error) {
	rows, err := q.query(ctx, q.listTraefikInstancesStmt, listTraefikInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TraefikInstance
	for rows.Next() {
		var i TraefikInstance
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Entrypoints,
			&i.Overview,
			&i.Config,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTraefikInstance = `-- name: UpdateTraefikInstance :one
UPDATE traefik_instances
SET
  entrypoints = ?,
  overview = ?,
  config = ?,
  version = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE
  id = ? RETURNING id, profile_id, entrypoints, overview, config, version, created_at, updated_at
`

type UpdateTraefikInstanceParams struct {
	Entrypoints *schema.EntryPoint    `json:"entrypoints"`
	Overview    *schema.Overview      `json:"overview"`
	Config      *schema.Configuration `json:"config"`
	Version     *string               `json:"version"`
	ID          int64                 `json:"id"`
}

func (q *Queries) UpdateTraefikInstance(ctx context.Context, arg UpdateTraefikInstanceParams) (TraefikInstance, error) {
	row := q.queryRow(ctx, q.updateTraefikInstanceStmt, updateTraefikInstance,
		arg.Entrypoints,
		arg.Overview,
		arg.Config,
		arg.Version,
		arg.ID,
	)
	var i TraefikInstance
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Entrypoints,
		&i.Overview,
		&i.Config,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
