when:
  - event: [push, tag, deployment, manual]
    branch: main

steps:
  - name: deploy-docs
    image: node:20
    commands:
      - git config --global user.name "${CI_COMMIT_AUTHOR}"
      - git config --global user.email "${CI_COMMIT_AUTHOR_EMAIL}"
      - echo "machine github.com login ${CI_COMMIT_AUTHOR} password ${GITHUB_TOKEN}" > ~/.netrc
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm config set store-dir .pnpm-store
      - cd docs
      - pnpm install
      - pnpm run build
      - pnpm run deploy
    environment:
      GIT_USER: ${CI_COMMIT_AUTHOR}
      GITHUB_TOKEN:
        from_secret: gh_token

