when:
  - branch: main
  - event: [push, tag, deployment, manual]

steps:
  - name: deploy-docs
    image: node:20
    commands:
      - git config --global user.name "${CI_COMMIT_AUTHOR}"
      - git config --global user.email "${CI_COMMIT_AUTHOR_EMAIL}"
      - echo "machine github.com login ${CI_COMMIT_AUTHOR} password ${GITHUB_TOKEN}" > ~/.netrc
      - chmod 600 ~/.netrc
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm config set store-dir .pnpm-store
      - cd docs
      - pnpm install
      - pnpm run build
      - pnpm run deploy
    environment:
      GITHUB_TOKEN:
        from_secret: gh_token

