when:
  - branch: main
    event: [push, tag, deployment, manual]

steps:
  - name: deploy-docs
    image: node:20
    commands:
      - mkdir -p $HOME/.ssh
      - ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
      - echo "$GITHUB_TOKEN" > "$HOME/.ssh/id_rsa"
      - chmod 0600 $HOME/.ssh/id_rsa
      - corepack enable
      - corepack prepare pnpm@latest --activate
      - pnpm config set store-dir .pnpm-store
      - cd docs
      - pnpm install
      - pnpm run build
      - pnpm run deploy
    environment:
      USE_SSH: true
      GITHUB_TOKEN:
        from_secret: gh_deploy_token

