// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Agent struct {
	ID         string     `json:"id"`
	ProfileID  int64      `json:"profileId"`
	Hostname   string     `json:"hostname"`
	PublicIp   *string    `json:"publicIp"`
	PrivateIps *string    `json:"privateIps"`
	Containers *string    `json:"containers"`
	ActiveIp   *string    `json:"activeIp"`
	Token      string     `json:"token"`
	LastSeen   *time.Time `json:"lastSeen"`
}

type Profile struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Url      string  `json:"url"`
	Username *string `json:"username"`
	Password *string `json:"password"`
	Tls      bool    `json:"tls"`
}

type Provider struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	Type       string  `json:"type"`
	ExternalIp string  `json:"externalIp"`
	ApiKey     string  `json:"apiKey"`
	ApiUrl     *string `json:"apiUrl"`
	ZoneType   *string `json:"zoneType"`
	Proxied    bool    `json:"proxied"`
	IsActive   bool    `json:"isActive"`
}

type RouterDnsProvider struct {
	ProfileID  int64  `json:"profileId"`
	ProviderID int64  `json:"providerId"`
	Name       string `json:"name"`
}

type Setting struct {
	ID    int64  `json:"id"`
	Key   string `json:"key"`
	Value string `json:"value"`
}

type TraefikApi struct {
	ProfileID   int64               `json:"profileId"`
	Entrypoints *TraefikEntryPoints `json:"entrypoints"`
	Overview    *TraefikOverview    `json:"overview"`
	External    *TraefikConfig      `json:"external"`
	Internal    *TraefikConfig      `json:"internal"`
}

type User struct {
	ID        int64      `json:"id"`
	Username  string     `json:"username"`
	Password  string     `json:"password"`
	Email     *string    `json:"email"`
	IsAdmin   bool       `json:"isAdmin"`
	LastLogin *time.Time `json:"lastLogin"`
}
