// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateSetting(ctx context.Context, arg CreateSettingParams) (Setting, error)
	DeleteAgentByID(ctx context.Context, id string) error
	DeleteInternalHTTPMiddleware(ctx context.Context, arg DeleteInternalHTTPMiddlewareParams) error
	DeleteInternalHTTPRouter(ctx context.Context, arg DeleteInternalHTTPRouterParams) error
	DeleteInternalHTTPService(ctx context.Context, arg DeleteInternalHTTPServiceParams) error
	DeleteInternalTCPMiddleware(ctx context.Context, arg DeleteInternalTCPMiddlewareParams) error
	DeleteInternalTCPRouter(ctx context.Context, arg DeleteInternalTCPRouterParams) error
	DeleteInternalTCPService(ctx context.Context, arg DeleteInternalTCPServiceParams) error
	DeleteInternalUDPRouter(ctx context.Context, arg DeleteInternalUDPRouterParams) error
	DeleteInternalUDPService(ctx context.Context, arg DeleteInternalUDPServiceParams) error
	DeleteProfileByID(ctx context.Context, id int64) error
	DeleteProviderByID(ctx context.Context, id int64) error
	DeleteSettingByID(ctx context.Context, id int64) error
	DeleteUserByID(ctx context.Context, id int64) error
	GetAgentByHostname(ctx context.Context, arg GetAgentByHostnameParams) (Agent, error)
	GetAgentByID(ctx context.Context, id string) (Agent, error)
	GetDefaultProvider(ctx context.Context) (Provider, error)
	GetExternalHTTPMiddlewareByName(ctx context.Context, arg GetExternalHTTPMiddlewareByNameParams) (interface{}, error)
	GetExternalHTTPMiddlewaresByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalHTTPRouterByName(ctx context.Context, arg GetExternalHTTPRouterByNameParams) (interface{}, error)
	GetExternalHTTPRoutersByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalHTTPServiceByName(ctx context.Context, arg GetExternalHTTPServiceByNameParams) (interface{}, error)
	GetExternalHTTPServicesByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalTCPMiddlewareByName(ctx context.Context, arg GetExternalTCPMiddlewareByNameParams) (interface{}, error)
	GetExternalTCPMiddlewaresByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalTCPRouterByName(ctx context.Context, arg GetExternalTCPRouterByNameParams) (interface{}, error)
	GetExternalTCPRoutersByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalTCPServiceByName(ctx context.Context, arg GetExternalTCPServiceByNameParams) (interface{}, error)
	GetExternalTCPServicesByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalTraefikConfigByProfileID(ctx context.Context, profileID int64) (*TraefikConfig, error)
	GetExternalUDPRouterByName(ctx context.Context, arg GetExternalUDPRouterByNameParams) (interface{}, error)
	GetExternalUDPRoutersByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetExternalUDPServiceByName(ctx context.Context, arg GetExternalUDPServiceByNameParams) (interface{}, error)
	GetExternalUDPServicesByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalHTTPMiddlewareByName(ctx context.Context, arg GetInternalHTTPMiddlewareByNameParams) (interface{}, error)
	GetInternalHTTPMiddlewaresByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalHTTPRouterByName(ctx context.Context, arg GetInternalHTTPRouterByNameParams) (interface{}, error)
	GetInternalHTTPRoutersByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalHTTPServiceByName(ctx context.Context, arg GetInternalHTTPServiceByNameParams) (interface{}, error)
	GetInternalHTTPServicesByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalTCPMiddlewareByName(ctx context.Context, arg GetInternalTCPMiddlewareByNameParams) (interface{}, error)
	GetInternalTCPMiddlewaresByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalTCPRouterByName(ctx context.Context, arg GetInternalTCPRouterByNameParams) (interface{}, error)
	GetInternalTCPRoutersByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalTCPServiceByName(ctx context.Context, arg GetInternalTCPServiceByNameParams) (interface{}, error)
	GetInternalTCPServicesByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalTraefikConfigByProfileID(ctx context.Context, profileID int64) (*TraefikConfig, error)
	GetInternalUDPRouterByName(ctx context.Context, arg GetInternalUDPRouterByNameParams) (interface{}, error)
	GetInternalUDPRoutersByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetInternalUDPServiceByName(ctx context.Context, arg GetInternalUDPServiceByNameParams) (interface{}, error)
	GetInternalUDPServicesByProfileID(ctx context.Context, profileID int64) (interface{}, error)
	GetProfileByID(ctx context.Context, id int64) (Profile, error)
	GetProfileByName(ctx context.Context, name string) (Profile, error)
	GetProviderByID(ctx context.Context, id int64) (Provider, error)
	GetSettingByKey(ctx context.Context, key string) (Setting, error)
	GetTraefikConfigByProfileID(ctx context.Context, profileID int64) (TraefikApi, error)
	GetTraefikEntrypointsByProfileID(ctx context.Context, profileID int64) (*TraefikEntryPoints, error)
	GetTraefikOverviewByProfileID(ctx context.Context, profileID int64) (*TraefikOverview, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAgents(ctx context.Context) ([]Agent, error)
	ListAgentsByProfileID(ctx context.Context, profileID int64) ([]Agent, error)
	ListProfiles(ctx context.Context) ([]Profile, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateSetting(ctx context.Context, arg UpdateSettingParams) (Setting, error)
	UpsertAgent(ctx context.Context, arg UpsertAgentParams) (Agent, error)
	UpsertInternalHTTPMiddleware(ctx context.Context, arg UpsertInternalHTTPMiddlewareParams) error
	UpsertInternalHTTPRouter(ctx context.Context, arg UpsertInternalHTTPRouterParams) error
	UpsertInternalHTTPService(ctx context.Context, arg UpsertInternalHTTPServiceParams) error
	UpsertInternalTCPMiddleware(ctx context.Context, arg UpsertInternalTCPMiddlewareParams) error
	UpsertInternalTCPRouter(ctx context.Context, arg UpsertInternalTCPRouterParams) error
	UpsertInternalTCPService(ctx context.Context, arg UpsertInternalTCPServiceParams) error
	UpsertInternalUDPRouter(ctx context.Context, arg UpsertInternalUDPRouterParams) error
	UpsertInternalUDPService(ctx context.Context, arg UpsertInternalUDPServiceParams) error
	UpsertProfile(ctx context.Context, arg UpsertProfileParams) (Profile, error)
	UpsertProvider(ctx context.Context, arg UpsertProviderParams) (Provider, error)
	UpsertTraefikConfig(ctx context.Context, arg UpsertTraefikConfigParams) (TraefikApi, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
