// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: router_dns_provider.sql

package db

import (
	"context"
)

const deleteRouterDNSProvider = `-- name: DeleteRouterDNSProvider :exec
DELETE FROM router_dns_provider
WHERE
  traefik_id = ?
  AND router_name = ?
`

type DeleteRouterDNSProviderParams struct {
	TraefikID  int64  `json:"traefikId"`
	RouterName string `json:"routerName"`
}

func (q *Queries) DeleteRouterDNSProvider(ctx context.Context, arg DeleteRouterDNSProviderParams) error {
	_, err := q.exec(ctx, q.deleteRouterDNSProviderStmt, deleteRouterDNSProvider, arg.TraefikID, arg.RouterName)
	return err
}

const getRouterDNSProvider = `-- name: GetRouterDNSProvider :one
SELECT
  rdp.traefik_id, rdp.provider_id, rdp.router_name,
  dp.name as provider_name,
  dp.type as provider_type
FROM
  router_dns_provider rdp
  JOIN dns_providers dp ON dp.id = rdp.provider_id
WHERE
  rdp.traefik_id = ?
  AND rdp.router_name = ?
`

type GetRouterDNSProviderParams struct {
	TraefikID  int64  `json:"traefikId"`
	RouterName string `json:"routerName"`
}

type GetRouterDNSProviderRow struct {
	TraefikID    int64  `json:"traefikId"`
	ProviderID   int64  `json:"providerId"`
	RouterName   string `json:"routerName"`
	ProviderName string `json:"providerName"`
	ProviderType string `json:"providerType"`
}

func (q *Queries) GetRouterDNSProvider(ctx context.Context, arg GetRouterDNSProviderParams) (GetRouterDNSProviderRow, error) {
	row := q.queryRow(ctx, q.getRouterDNSProviderStmt, getRouterDNSProvider, arg.TraefikID, arg.RouterName)
	var i GetRouterDNSProviderRow
	err := row.Scan(
		&i.TraefikID,
		&i.ProviderID,
		&i.RouterName,
		&i.ProviderName,
		&i.ProviderType,
	)
	return i, err
}

const listRouterDNSProvidersByTraefikID = `-- name: ListRouterDNSProvidersByTraefikID :many
SELECT
  rdp.traefik_id, rdp.provider_id, rdp.router_name,
  dp.name as provider_name,
  dp.type as provider_type
FROM
  router_dns_provider rdp
  JOIN dns_providers dp ON dp.id = rdp.provider_id
WHERE
  rdp.traefik_id = ?
`

type ListRouterDNSProvidersByTraefikIDRow struct {
	TraefikID    int64  `json:"traefikId"`
	ProviderID   int64  `json:"providerId"`
	RouterName   string `json:"routerName"`
	ProviderName string `json:"providerName"`
	ProviderType string `json:"providerType"`
}

func (q *Queries) ListRouterDNSProvidersByTraefikID(ctx context.Context, traefikID int64) ([]ListRouterDNSProvidersByTraefikIDRow, error) {
	rows, err := q.query(ctx, q.listRouterDNSProvidersByTraefikIDStmt, listRouterDNSProvidersByTraefikID, traefikID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRouterDNSProvidersByTraefikIDRow
	for rows.Next() {
		var i ListRouterDNSProvidersByTraefikIDRow
		if err := rows.Scan(
			&i.TraefikID,
			&i.ProviderID,
			&i.RouterName,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRouterDNSProvider = `-- name: UpsertRouterDNSProvider :exec
INSERT INTO
  router_dns_provider (traefik_id, provider_id, router_name)
VALUES
  (?, ?, ?) ON CONFLICT (traefik_id, router_name) DO
UPDATE
SET
  provider_id = EXCLUDED.provider_id
`

type UpsertRouterDNSProviderParams struct {
	TraefikID  int64  `json:"traefikId"`
	ProviderID int64  `json:"providerId"`
	RouterName string `json:"routerName"`
}

func (q *Queries) UpsertRouterDNSProvider(ctx context.Context, arg UpsertRouterDNSProviderParams) error {
	_, err := q.exec(ctx, q.upsertRouterDNSProviderStmt, upsertRouterDNSProvider, arg.TraefikID, arg.ProviderID, arg.RouterName)
	return err
}
