// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: traefik.sql

package db

import (
	"context"

	"github.com/MizuchiLabs/mantrae/internal/source"
	"github.com/traefik/traefik/v3/pkg/config/dynamic"
)

const createTraefikConfig = `-- name: CreateTraefikConfig :exec
INSERT INTO
    traefik (profile_id, source, entrypoints, overview, config)
VALUES
    (?, ?, ?, ?, ?)
`

type CreateTraefikConfigParams struct {
	ProfileID   int64                  `json:"profileId"`
	Source      source.Source          `json:"source"`
	Entrypoints *TraefikEntryPoints    `json:"entrypoints"`
	Overview    *TraefikOverview       `json:"overview"`
	Config      *dynamic.Configuration `json:"config"`
}

func (q *Queries) CreateTraefikConfig(ctx context.Context, arg CreateTraefikConfigParams) error {
	_, err := q.exec(ctx, q.createTraefikConfigStmt, createTraefikConfig,
		arg.ProfileID,
		arg.Source,
		arg.Entrypoints,
		arg.Overview,
		arg.Config,
	)
	return err
}

const deleteTraefikConfig = `-- name: DeleteTraefikConfig :exec
DELETE FROM traefik
WHERE
    id = ?
`

func (q *Queries) DeleteTraefikConfig(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteTraefikConfigStmt, deleteTraefikConfig, id)
	return err
}

const getTraefikConfig = `-- name: GetTraefikConfig :one
SELECT
    id, profile_id, source, entrypoints, overview, config, created_at, updated_at
FROM
    traefik
WHERE
    id = ?
`

func (q *Queries) GetTraefikConfig(ctx context.Context, id int64) (Traefik, error) {
	row := q.queryRow(ctx, q.getTraefikConfigStmt, getTraefikConfig, id)
	var i Traefik
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Source,
		&i.Entrypoints,
		&i.Overview,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTraefikConfigBySource = `-- name: GetTraefikConfigBySource :one
SELECT
    id, profile_id, source, entrypoints, overview, config, created_at, updated_at
FROM
    traefik
WHERE
    profile_id = ?
    AND source = ?
`

type GetTraefikConfigBySourceParams struct {
	ProfileID int64         `json:"profileId"`
	Source    source.Source `json:"source"`
}

func (q *Queries) GetTraefikConfigBySource(ctx context.Context, arg GetTraefikConfigBySourceParams) (Traefik, error) {
	row := q.queryRow(ctx, q.getTraefikConfigBySourceStmt, getTraefikConfigBySource, arg.ProfileID, arg.Source)
	var i Traefik
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Source,
		&i.Entrypoints,
		&i.Overview,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTraefikConfig = `-- name: UpdateTraefikConfig :exec
UPDATE traefik
SET
    source = ?,
    entrypoints = ?,
    overview = ?,
    config = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

type UpdateTraefikConfigParams struct {
	Source      source.Source          `json:"source"`
	Entrypoints *TraefikEntryPoints    `json:"entrypoints"`
	Overview    *TraefikOverview       `json:"overview"`
	Config      *dynamic.Configuration `json:"config"`
	ID          int64                  `json:"id"`
}

func (q *Queries) UpdateTraefikConfig(ctx context.Context, arg UpdateTraefikConfigParams) error {
	_, err := q.exec(ctx, q.updateTraefikConfigStmt, updateTraefikConfig,
		arg.Source,
		arg.Entrypoints,
		arg.Overview,
		arg.Config,
		arg.ID,
	)
	return err
}
