name: Actionlint
on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
  push:
    branches: [main]
    paths:
      - ".github/workflows/*.yml"
      - ".github/workflows/*.yaml"
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Run Actionlint
        uses: raven-actions/actionlint@v2
